name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - langs/**
      - libs/**
      - main.mjs

jobs:
  libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: commit
        continue-on-error: true
        run: |
          git config --global user.email ""
          git config --global user.name "Library Deployer"
          node main.mjs
          git add README.md
          git commit -m "Deploy $GITHUB_SHA"
      - if: steps.commit.outcome == 'success' && steps.commit.conclusion == 'success'
        run: git push
