name: Sort Library List

on:
  push:
    branches: [ master ]

jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Run sort script
        run: node sort.js
      - name: Commit changes
        id: commit
        continue-on-error: true
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Sort library list alphabetically"
      - name: Push changes
        if: steps.commit.outcome == 'success' && steps.commit.conclusion == 'success'
        uses: ad-m/github-push-action@8407731efefc0d8f72af254c74276b7a90be36e1